### PR TITLE
Add patch priviliges for PV and PVCs

### PR DESCRIPTION
**Pull request by NotANormalNerd**
Fixes everything not already fixed on master in #96

### CODE REVIEW

**Comment by NotANormalNerd** [comment]
This is sadly not stale. Let me know what is needed.

**Comment by JannikZed** [comment]
PLEASE MERGE HETZNER!

**Comment by toabi** [comment]
@LKaemmerling would be cool if this and #96 could get some attention

**Comment by LKaemmerling** [comment]
Sorry for the long waiting time. I will prepare a release in the next few minutes.

**Pull request merged**
